//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RusaMiaChairmanBari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C100TakaData
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> TotalMonth { get; set; }
        public Nullable<int> Amount { get; set; }
        public string NameOfPaidMonth { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
