//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RusaMiaChairmanBari.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RusaMiaBariDBEntities : DbContext
    {
        public RusaMiaBariDBEntities()
            : base("name=RusaMiaBariDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C50TakaData> C50TakaData { get; set; }
        public virtual DbSet<Admin_table> Admin_table { get; set; }
        public virtual DbSet<C100TakaData> C100TakaData { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
    }
}
